/* ============================================================
   Banque TOEIC partagée — SOURCE UNIQUE
   Utilisée par index.html (site) ET les mini-jeux.
   Pour ajouter du contenu, modifie ICI uniquement.
   ============================================================ */
window.TOEIC_BANK = window.TOEIC_BANK || {};
window.TOEIC_BANK.VOCAB = [
 {w:"recruitment",ipa:"/rɪˈkruːt.mənt/",fr:"recrutement",ex:"The recruitment process takes approximately four weeks.",col:["recruitment campaign","recruitment process","recruitment agency","recruitment drive"],t:"RH & recrutement"},
 {w:"applicant",ipa:"/ˈæp.lɪ.kənt/",fr:"candidat",ex:"All applicants must submit a cover letter.",col:["successful applicant","qualified applicant","job applicant"],t:"RH & recrutement"},
 {w:"candidate",ipa:"/ˈkæn.dɪ.deɪt/",fr:"candidat",ex:"The candidate impressed the interview panel.",col:["shortlisted candidate","ideal candidate","strong candidate"],t:"RH & recrutement"},
 {w:"vacancy",ipa:"/ˈveɪ.kən.si/",fr:"poste vacant",ex:"The company has several vacancies in its sales department.",col:["job vacancy","fill a vacancy","current vacancy"],t:"RH & recrutement"},
 {w:"resume (us) / cv (uk)",ipa:"/ˈrez.ə.meɪ/",fr:"CV",ex:"Please attach your resume to the application form.",col:["update a resume","submit a resume","resume screening"],t:"RH & recrutement"},
 {w:"cover letter",ipa:"/ˈkʌv.ər ˌlet.ər/",fr:"lettre de motivation",ex:"A strong cover letter can improve your chances of being selected.",col:["write a cover letter","personalised cover letter"],t:"RH & recrutement"},
 {w:"interview",ipa:"/ˈɪn.tə.vjuː/",fr:"entretien d'embauche",ex:"She was invited to a second interview.",col:["job interview","interview panel","conduct an interview","interview questions"],t:"RH & recrutement"},
 {w:"qualification",ipa:"/ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/",fr:"qualification",ex:"The position requires professional qualifications.",col:["academic qualifications","professional qualifications","required qualifications"],t:"RH & recrutement"},
 {w:"experience",ipa:"/ɪkˈspɪə.ri.əns/",fr:"expérience",ex:"Previous experience is highly desirable.",col:["work experience","relevant experience","extensive experience"],t:"RH & recrutement"},
 {w:"skills",ipa:"/skɪlz/",fr:"compétences",ex:"Communication skills are essential for this role.",col:["technical skills","interpersonal skills","leadership skills","transferable skills"],t:"RH & recrutement"},
 {w:"promotion",ipa:"/prəˈməʊ.ʃən/",fr:"promotion",ex:"She received a promotion after three years.",col:["earn a promotion","promotion opportunity","promotion policy"],t:"RH & recrutement"},
 {w:"salary",ipa:"/ˈsæl.ər.i/",fr:"salaire",ex:"The salary is competitive.",col:["annual salary","salary increase","salary package"],t:"RH & recrutement"},
 {w:"benefits",ipa:"/ˈben.ɪ.fɪts/",fr:"avantages sociaux",ex:"The company offers excellent employee benefits.",col:["health benefits","retirement benefits","employee benefits package"],t:"RH & recrutement"},
 {w:"payroll",ipa:"/ˈpeɪ.rəʊl/",fr:"paie",ex:"Payroll is processed at the end of each month.",col:["payroll department","payroll records","payroll costs"],t:"RH & recrutement"},
 {w:"resignation",ipa:"/ˌrez.ɪɡˈneɪ.ʃən/",fr:"démission",ex:"The manager announced his resignation.",col:["submit a resignation","resignation letter","TOEIC EXERCISE","Match the word and definition"],t:"RH & recrutement"},
 {w:"revenue",ipa:"/ˈrev.ə.njuː/",fr:"chiffre d'affaires, revenu",ex:"The company reported increased revenue this quarter.",col:["annual revenue","generate revenue","revenue growth","revenue stream"],t:"Finance & comptabilité"},
 {w:"profit",ipa:"/ˈprɒf.ɪt/",fr:"bénéfice",ex:"The company made a substantial profit.",col:["net profit","profit margin","profit forecast","increase profits"],t:"Finance & comptabilité"},
 {w:"loss",ipa:"/lɒs/",fr:"perte",ex:"The company suffered a financial loss.",col:["net loss","operating loss","record a loss"],t:"Finance & comptabilité"},
 {w:"budget",ipa:"/ˈbʌdʒ.ɪt/",fr:"budget",ex:"The marketing budget was increased.",col:["annual budget","budget proposal","budget cuts","stay within budget"],t:"Finance & comptabilité"},
 {w:"expenditure",ipa:"/ɪkˈspen.dɪ.tʃər/",fr:"dépenses",ex:"Government expenditure increased last year.",col:["capital expenditure","operating expenditure","reduce expenditure"],t:"Finance & comptabilité"},
 {w:"expense",ipa:"/ɪkˈspens/",fr:"frais, dépense",ex:"Travel expenses will be reimbursed.",col:["business expenses","travel expenses","expense report"],t:"Finance & comptabilité"},
 {w:"invoice",ipa:"/ˈɪn.vɔɪs/",fr:"facture",ex:"The invoice must be paid within 30 days.",col:["issue an invoice","unpaid invoice","invoice number","⚠ TOEIC Favorite Word"],t:"Finance & comptabilité"},
 {w:"receipt",ipa:"/rɪˈsiːt/",fr:"reçu",ex:"Please keep your receipt.",col:["sales receipt","receipt number","provide a receipt","⚠ Important"],t:"Finance & comptabilité"},
 {w:"payment",ipa:"/ˈpeɪ.mənt/",fr:"paiement",ex:"Payment is due on June 30.",col:["make a payment","payment deadline","payment method"],t:"Finance & comptabilité"},
 {w:"refund",ipa:"/ˈriː.fʌnd/",fr:"remboursement",ex:"Customers may request a refund.",col:["full refund","partial refund","refund policy"],t:"Finance & comptabilité"},
 {w:"asset",ipa:"/ˈæs.et/",fr:"actif",ex:"Real estate is an important asset.",col:["company assets","financial assets","asset management"],t:"Finance & comptabilité"},
 {w:"liability",ipa:"/ˌlaɪ.əˈbɪl.ə.ti/",fr:"passif, dette",ex:"The company's liabilities increased.",col:["financial liabilities","current liabilities"],t:"Finance & comptabilité"},
 {w:"debt",ipa:"/det/",fr:"dette",ex:"The company reduced its debt.",col:["outstanding debt","debt repayment","debt management"],t:"Finance & comptabilité"},
 {w:"loan",ipa:"/ləʊn/",fr:"prêt",ex:"The company obtained a loan.",col:["bank loan","loan application","loan repayment"],t:"Finance & comptabilité"},
 {w:"interest rate",ipa:"/ˈɪn.trəst reɪt/",fr:"taux d'intérêt",ex:"Interest rates have risen recently.",col:["fixed interest rate","variable interest rate"],t:"Finance & comptabilité"},
 {w:"shareholder",ipa:"/ˈʃeəˌhəʊl.dər/",fr:"actionnaire",ex:"Shareholders approved the proposal.",col:["major shareholder","shareholder meeting"],t:"Finance & comptabilité"},
 {w:"stock",ipa:"/stɒk/",fr:"action, titre",ex:"The company's stock price increased.",col:["stock market","stock price","stock exchange","⚠ TOEIC Trap"],t:"Finance & comptabilité"},
 {w:"merger",ipa:"/ˈmɜː.dʒər/",fr:"fusion",ex:"The merger created a larger organisation.",col:["company merger","merger agreement"],t:"Finance & comptabilité"},
 {w:"acquisition",ipa:"/ˌæk.wɪˈzɪʃ.ən/",fr:"acquisition",ex:"The acquisition expanded the firm's market share.",col:["strategic acquisition","acquisition deal"],t:"Finance & comptabilité"},
 {w:"investment",ipa:"/ɪnˈvest.mənt/",fr:"investissement",ex:"The project requires significant investment.",col:["foreign investment","investment strategy","investment portfolio","TOEIC COLLOCATIONS"],t:"Finance & comptabilité"},
 {w:"logistics",ipa:"/ləˈdʒɪs.tɪks/",fr:"logistique",ex:"The logistics department coordinates deliveries worldwide.",col:["logistics manager","logistics network","logistics operations"],t:"Logistique"},
 {w:"supply chain",ipa:"/səˈplaɪ tʃeɪn/",fr:"chaîne d'approvisionnement",ex:"The company improved its supply chain efficiency.",col:["global supply chain","supply chain management","supply chain disruption"],t:"Logistique"},
 {w:"supplier",ipa:"/səˈplaɪ.ər/",fr:"fournisseur",ex:"The supplier delivered the goods on time.",col:["reliable supplier","local supplier","supplier contract"],t:"Logistique"},
 {w:"vendor",ipa:"/ˈven.dər/",fr:"vendeur, fournisseur",ex:"The vendor offered a competitive price.",col:["approved vendor","software vendor"],t:"Logistique"},
 {w:"procurement",ipa:"/prəˈkjʊə.mənt/",fr:"approvisionnement, achat",ex:"Procurement costs increased this year.",col:["procurement process","procurement department"],t:"Logistique"},
 {w:"order",ipa:"/ˈɔː.dər/",fr:"commande",ex:"The customer placed an order online.",col:["place an order","cancel an order","order confirmation","order number"],t:"Logistique"},
 {w:"purchase order (po)",ipa:"/ˈpɜː.tʃəs ˌɔː.dər/",fr:"bon de commande",ex:"The supplier received the purchase order yesterday.",col:["issue a purchase order","purchase order number"],t:"Logistique"},
 {w:"shipment",ipa:"/ˈʃɪp.mənt/",fr:"expédition",ex:"The shipment arrived ahead of schedule.",col:["international shipment","shipment tracking","shipment delay"],t:"Logistique"},
 {w:"delivery",ipa:"/dɪˈlɪv.ər.i/",fr:"livraison",ex:"Delivery is expected next week.",col:["delivery service","delivery date","express delivery"],t:"Logistique"},
 {w:"carrier",ipa:"/ˈkær.i.ər/",fr:"transporteur",ex:"The carrier reported a delay.",col:["shipping carrier","air carrier","freight carrier"],t:"Logistique"},
 {w:"freight",ipa:"/freɪt/",fr:"fret, marchandise",ex:"Freight costs have increased.",col:["air freight","sea freight","freight charges"],t:"Logistique"},
 {w:"warehouse",ipa:"/ˈweə.haʊs/",fr:"entrepôt",ex:"Products are stored in the warehouse.",col:["warehouse manager","warehouse inventory","warehouse operations"],t:"Logistique"},
 {w:"inventory",ipa:"/ˈɪn.vən.tər.i/",fr:"inventaire",ex:"The inventory is updated weekly.",col:["inventory management","inventory levels","inventory control","⚠️ TOEIC Favorite Word"],t:"Logistique"},
 {w:"backorder",ipa:"/ˈbækˌɔː.dər/",fr:"commande en attente",ex:"The product is on backorder.",col:["place on backorder","backorder notice"],t:"Logistique"},
 {w:"dispatch",ipa:"/dɪˈspætʃ/",fr:"expédier",ex:"The goods were dispatched yesterday.",col:["dispatch department","dispatch goods"],t:"Logistique"},
 {w:"tracking number",ipa:"/ˈtræk.ɪŋ ˌnʌm.bər/",fr:"numéro de suivi",ex:"Customers receive a tracking number by email.",col:["tracking information","shipment tracking"],t:"Logistique"},
 {w:"customs",ipa:"/ˈkʌs.təmz/",fr:"douanes",ex:"The package is being held by customs.",col:["customs clearance","customs declaration"],t:"Logistique"},
 {w:"import",ipa:"/ˈɪm.pɔːt/",fr:"importation",ex:"The company imports products from Asia.",col:["import duties","import licence"],t:"Logistique"},
 {w:"export",ipa:"/ˈek.spɔːt/",fr:"exportation",ex:"Exports increased by 10% this year.",col:["export market","export licence","export department","TOEIC SUPER COLLOCATIONS"],t:"Logistique"},
 {w:"correspondence",ipa:"/ˌkɒr.ɪˈspɒn.dəns/",fr:"correspondance",ex:"All correspondence should be kept on file.",col:["business correspondence","official correspondence"],t:"E-mails"},
 {w:"recipient",ipa:"/rɪˈsɪp.i.ənt/",fr:"destinataire",ex:"The recipient confirmed receipt of the email.",col:["email recipient","intended recipient"],t:"E-mails"},
 {w:"sender",ipa:"/ˈsen.dər/",fr:"expéditeur",ex:"The sender requested additional information.",col:["original sender","sender information"],t:"E-mails"},
 {w:"inquiry",ipa:"/ɪnˈkwaɪə.ri/",fr:"demande de renseignements",ex:"We received an inquiry about the product.",col:["customer inquiry","inquiry form"],t:"E-mails"},
 {w:"request",ipa:"/rɪˈkwest/",fr:"demande",ex:"Your request has been approved.",col:["submit a request","request information","special request"],t:"E-mails"},
 {w:"confirmation",ipa:"/ˌkɒn.fəˈmeɪ.ʃən/",fr:"confirmation",ex:"Please send confirmation by email.",col:["booking confirmation","confirmation email"],t:"E-mails"},
 {w:"notification",ipa:"/ˌnəʊ.tɪ.fɪˈkeɪ.ʃən/",fr:"notification",ex:"Customers received a notification.",col:["email notification","automatic notification"],t:"E-mails"},
 {w:"reminder",ipa:"/rɪˈmaɪn.dər/",fr:"rappel",ex:"This is a reminder regarding your appointment.",col:["payment reminder","reminder email"],t:"E-mails"},
 {w:"attachment",ipa:"/əˈtætʃ.mənt/",fr:"pièce jointe",ex:"The attachment contains the report.",col:["attached document","email attachment"],t:"E-mails"},
 {w:"forward",ipa:"/ˈfɔː.wəd/",fr:"transférer",ex:"Please forward the email to the finance department.",col:["forward an email","forward information"],t:"E-mails"},
 {w:"reply",ipa:"/rɪˈplaɪ/",fr:"répondre",ex:"Please reply by Friday.",col:["reply promptly","reply to an email"],t:"E-mails"},
 {w:"enclosure",ipa:"/ɪnˈkləʊ.ʒər/",fr:"document joint",ex:"Please see the enclosed brochure.",col:["enclosed document","enclosed form"],t:"E-mails"},
 {w:"brochure",ipa:"/ˈbrəʊ.ʃər/",fr:"brochure",ex:"The brochure describes our services.",col:["promotional brochure","information brochure"],t:"E-mails"},
 {w:"announcement",ipa:"/əˈnaʊns.mənt/",fr:"annonce",ex:"The company made an important announcement.",col:["official announcement","public announcement"],t:"E-mails"},
 {w:"newsletter",ipa:"/ˈnjuːzˌlet.ər/",fr:"lettre d'information",ex:"Employees receive a monthly newsletter.",col:["company newsletter","monthly newsletter"],t:"E-mails"},
 {w:"subscription",ipa:"/səbˈskrɪp.ʃən/",fr:"abonnement",ex:"The subscription expires next month.",col:["annual subscription","subscription fee"],t:"E-mails"},
 {w:"complaint",ipa:"/kəmˈpleɪnt/",fr:"réclamation",ex:"The customer filed a complaint.",col:["customer complaint","complaint procedure"],t:"E-mails"},
 {w:"refund request",ipa:"/ˈriː.fʌnd rɪˈkwest/",fr:"demande de remboursement",ex:"The refund request was approved.",col:["process a refund request","submit a refund request"],t:"E-mails"},
 {w:"follow-up",ipa:"/ˈfɒl.əʊ ʌp/",fr:"suivi",ex:"I am writing as a follow-up to our meeting.",col:["follow-up email","follow-up call","⚠️ TOEIC SUPER WORD"],t:"E-mails"},
 {w:"deadline extension",ipa:"/ˈded.laɪn ɪkˈsten.ʃən/",fr:"prolongation de délai",ex:"The deadline extension was approved.",col:["request an extension","grant an extension","TOEIC EMAIL EXPRESSIONS","Très fréquentes :"],t:"E-mails"},
 {w:"bank account",ipa:"/bæŋk əˈkaʊnt/",fr:"compte bancaire",ex:"The salary will be deposited into your bank account.",col:["current account","bank account number","business account"],t:"Banque & assurance"},
 {w:"deposit",ipa:"/dɪˈpɒz.ɪt/",fr:"dépôt",ex:"The deposit was credited immediately.",col:["security deposit","cash deposit","deposit funds"],t:"Banque & assurance"},
 {w:"withdrawal",ipa:"/wɪðˈdrɔː.əl/",fr:"retrait",ex:"ATM withdrawals are limited.",col:["cash withdrawal","withdrawal limit"],t:"Banque & assurance"},
 {w:"balance",ipa:"/ˈbæl.əns/",fr:"solde",ex:"Please check your account balance.",col:["account balance","available balance"],t:"Banque & assurance"},
 {w:"transfer",ipa:"/ˈtræns.fɜːr/",fr:"virement",ex:"The transfer was completed successfully.",col:["bank transfer","wire transfer","international transfer"],t:"Banque & assurance"},
 {w:"mortgage",ipa:"/ˈmɔː.ɡɪdʒ/",fr:"prêt immobilier",ex:"They applied for a mortgage.",col:["mortgage payment","mortgage application"],t:"Banque & assurance"},
 {w:"premium",ipa:"/ˈpriː.mi.əm/",fr:"prime d'assurance",ex:"Insurance premiums increased.",col:["annual premium","insurance premium"],t:"Banque & assurance"},
 {w:"insurance policy",ipa:"/ɪnˈʃʊə.rəns ˈpɒl.ə.si/",fr:"contrat d'assurance",ex:"The policy covers theft and fire.",col:["insurance policy","policy holder"],t:"Banque & assurance"},
 {w:"claim",ipa:"/kleɪm/",fr:"déclaration de sinistre",ex:"The customer filed a claim.",col:["insurance claim","claim form","claim settlement"],t:"Banque & assurance"},
 {w:"compensation",ipa:"/ˌkɒm.penˈseɪ.ʃən/",fr:"indemnisation",ex:"Compensation was granted.",col:["financial compensation","compensation package"],t:"Banque & assurance"},
 {w:"coverage",ipa:"/ˈkʌv.ər.ɪdʒ/",fr:"couverture",ex:"The policy offers full coverage.",col:["insurance coverage","full coverage"],t:"Banque & assurance"},
 {w:"policyholder",ipa:"/ˈpɒl.ə.siˌhəʊl.dər/",fr:"assuré",ex:"The policyholder contacted the insurer.",col:["policyholder information","policyholder benefits"],t:"Banque & assurance"},
 {w:"beneficiary",ipa:"/ˌben.ɪˈfɪʃ.ər.i/",fr:"bénéficiaire",ex:"The beneficiary received payment.",col:["designated beneficiary","beneficiary information"],t:"Banque & assurance"},
 {w:"interest",ipa:"/ˈɪn.trəst/",fr:"intérêt",ex:"The account earns interest.",col:["interest rate","compound interest"],t:"Banque & assurance"},
 {w:"credit",ipa:"/ˈkred.ɪt/",fr:"crédit",ex:"The bank approved the credit application.",col:["credit card","credit limit","credit score"],t:"Banque & assurance"},
 {w:"debit",ipa:"/ˈdeb.ɪt/",fr:"débit",ex:"The debit appeared on the statement.",col:["debit card","direct debit"],t:"Banque & assurance"},
 {w:"statement",ipa:"/ˈsteɪt.mənt/",fr:"relevé",ex:"The monthly statement is available online.",col:["bank statement","account statement"],t:"Banque & assurance"},
 {w:"fraud",ipa:"/frɔːd/",fr:"fraude",ex:"The bank detected fraud.",col:["credit card fraud","fraud investigation"],t:"Banque & assurance"},
 {w:"financial adviser",ipa:"/faɪˈnæn.ʃəl ədˈvaɪ.zər/",fr:"conseiller financier",ex:"The financial adviser reviewed the portfolio.",col:["independent financial adviser","financial advice"],t:"Banque & assurance"},
 {w:"portfolio",ipa:"/pɔːtˈfəʊ.li.əʊ/",fr:"portefeuille d'investissements",ex:"The portfolio performed well.",col:["investment portfolio","diversified portfolio","TOEIC SUPER COLLOCATIONS","open a bank account"],t:"Banque & assurance"},
 {w:"accurate",ipa:"/ˈæk.jə.rət/",fr:"précis, exact",ex:"The report contains accurate information.",col:["accurate data","accurate information"],t:"Adjectifs"},
 {w:"appropriate",ipa:"/əˈprəʊ.pri.ət/",fr:"approprié",ex:"Please wear appropriate clothing.",col:["appropriate action","appropriate response"],t:"Adjectifs"},
 {w:"beneficial",ipa:"/ˌben.ɪˈfɪʃ.əl/",fr:"bénéfique",ex:"The changes were beneficial.",col:["beneficial effect","mutually beneficial"],t:"Adjectifs"},
 {w:"capable",ipa:"/ˈkeɪ.pə.bəl/",fr:"capable",ex:"She is capable of managing the project.",col:["capable employee","fully capable"],t:"Adjectifs"},
 {w:"consistent",ipa:"/kənˈsɪs.tənt/",fr:"constant, cohérent",ex:"Sales showed consistent growth.",col:["consistent quality","consistent performance"],t:"Adjectifs"},
 {w:"current",ipa:"/ˈkʌr.ənt/",fr:"actuel",ex:"Please provide your current address.",col:["current employee","current situation"],t:"Adjectifs"},
 {w:"diverse",ipa:"/daɪˈvɜːs/",fr:"diversifié",ex:"The company has a diverse workforce.",col:["diverse team","diverse background"],t:"Adjectifs"},
 {w:"durable",ipa:"/ˈdjʊə.rə.bəl/",fr:"durable, résistant",ex:"The equipment is highly durable.",col:["durable product","durable materials"],t:"Adjectifs"},
 {w:"essential",ipa:"/ɪˈsen.ʃəl/",fr:"essentiel",ex:"Communication skills are essential.",col:["essential requirement","essential information"],t:"Adjectifs"},
 {w:"external",ipa:"/ɪkˈstɜː.nəl/",fr:"externe",ex:"External consultants were hired.",col:["external supplier","external audit"],t:"Adjectifs"},
 {w:"internal",ipa:"/ɪnˈtɜː.nəl/",fr:"interne",ex:"The vacancy was filled internally.",col:["internal communication","internal policy"],t:"Adjectifs"},
 {w:"mandatory",ipa:"/ˈmæn.də.tər.i/",fr:"obligatoire",ex:"Attendance is mandatory.",col:["mandatory training","mandatory requirement"],t:"Adjectifs"},
 {w:"mutual",ipa:"/ˈmjuː.tʃu.əl/",fr:"mutuel",ex:"The agreement was mutually beneficial.",col:["mutual agreement","mutual understanding"],t:"Adjectifs"},
 {w:"nationwide",ipa:"/ˌneɪ.ʃənˈwaɪd/",fr:"à l'échelle nationale",ex:"The campaign was launched nationwide.",col:["nationwide service","nationwide network"],t:"Adjectifs"},
 {w:"outstanding",ipa:"/aʊtˈstæn.dɪŋ/",fr:"en attente, impayé",ex:"Several outstanding invoices remain unpaid.",col:["outstanding balance","outstanding invoice","⚠️ Deuxième sens très fréquent au TOEIC."],t:"Adjectifs"},
 {w:"potential",ipa:"/pəˈten.ʃəl/",fr:"potentiel",ex:"The company contacted potential clients.",col:["potential customer","potential risk"],t:"Adjectifs"},
 {w:"previous",ipa:"/ˈpriː.vi.əs/",fr:"précédent",ex:"Please refer to our previous email.",col:["previous experience","previous version"],t:"Adjectifs"},
 {w:"relevant",ipa:"/ˈrel.ə.vənt/",fr:"pertinent",ex:"Please provide relevant information.",col:["relevant experience","relevant skills"],t:"Adjectifs"},
 {w:"secure",ipa:"/sɪˈkjʊər/",fr:"sécurisé",ex:"The system is secure.",col:["secure payment","secure access"],t:"Adjectifs"},
 {w:"unique",ipa:"/juːˈniːk/",fr:"unique",ex:"The company offers a unique service.",col:["unique opportunity","unique feature","TOEIC SUPER COLLOCATIONS","accurate information"],t:"Adjectifs"},
 {w:"because",ipa:"/bɪˈkɒz/",fr:"parce que",ex:"The meeting was cancelled because the manager was ill.",t:"Prépositions & connecteurs"},
 {w:"because of",ipa:"/bɪˈkɒz əv/",fr:"à cause de",ex:"The meeting was cancelled because of the storm.",t:"Prépositions & connecteurs"},
 {w:"although",ipa:"/ɔːlˈðəʊ/",fr:"bien que",ex:"Although sales declined, profits remained stable.",t:"Prépositions & connecteurs"},
 {w:"however",ipa:"/haʊˈev.ər/",fr:"cependant",ex:"Sales declined. However, profits remained stable.",t:"Prépositions & connecteurs"},
 {w:"despite",ipa:"/dɪˈspaɪt/",fr:"malgré",ex:"Despite the delay, the project succeeded.",t:"Prépositions & connecteurs"},
 {w:"in spite of",ipa:"/ɪn spaɪt əv/",fr:"malgré",ex:"In spite of the rain, the event continued.",t:"Prépositions & connecteurs"},
 {w:"therefore",ipa:"/ˈðeə.fɔːr/",fr:"par conséquent",ex:"Demand increased; therefore, production was expanded.",t:"Prépositions & connecteurs"},
 {w:"consequently",ipa:"/ˈkɒn.sɪ.kwənt.li/",fr:"par conséquent",ex:"Costs rose. Consequently, prices increased.",t:"Prépositions & connecteurs"},
 {w:"furthermore",ipa:"/ˌfɜː.ðəˈmɔːr/",fr:"de plus",ex:"The proposal is cost-effective. Furthermore, it is easy to implement.",t:"Prépositions & connecteurs"},
 {w:"moreover",ipa:"/mɔːˈrəʊ.vər/",fr:"de plus",ex:"The product is affordable. Moreover, it is durable.",t:"Prépositions & connecteurs"},
 {w:"whereas",ipa:"/weərˈæz/",fr:"alors que",ex:"Sales increased, whereas costs decreased.",t:"Prépositions & connecteurs"},
 {w:"while",ipa:"/waɪl/",fr:"alors que, pendant que",ex:"While profits increased, expenses remained stable.",t:"Prépositions & connecteurs"},
 {w:"during",ipa:"/ˈdjʊə.rɪŋ/",fr:"pendant",ex:"The incident occurred during the meeting.",t:"Prépositions & connecteurs"},
 {w:"since",ipa:"/sɪns/",fr:"depuis / puisque",ex:"She has worked here since 2022.",t:"Prépositions & connecteurs"},
 {w:"for",ipa:"/fɔːr/",fr:"pendant",ex:"She has worked here for three years.",t:"Prépositions & connecteurs"},
 {w:"by",ipa:"/baɪ/",fr:"d'ici",ex:"Please submit the report by Friday.",t:"Prépositions & connecteurs"},
 {w:"until",ipa:"/ənˈtɪl/",fr:"jusqu'à",ex:"The office will remain closed until Monday.",t:"Prépositions & connecteurs"},
 {w:"due to",ipa:"/djuː tuː/",fr:"en raison de",ex:"The flight was delayed due to bad weather.",t:"Prépositions & connecteurs"},
 {w:"owing to",ipa:"/ˈəʊ.ɪŋ tuː/",fr:"en raison de",ex:"The event was cancelled owing to technical issues.",t:"Prépositions & connecteurs"},
 {w:"carry out",ipa:"/ˈkæri aʊt/",fr:"effectuer, mener à bien",ex:"The company carried out a survey.",col:["carry out research","carry out an audit","carry out an investigation"],t:"Phrasal verbs"},
 {w:"set up",ipa:"/set ʌp/",fr:"mettre en place",ex:"The IT department set up the new system.",col:["set up a meeting","set up an account","set up equipment"],t:"Phrasal verbs"},
 {w:"take over",ipa:"/teɪk ˈəʊvə/",fr:"reprendre, racheter",ex:"A larger company took over the business.",col:["take over a company","take over responsibilities"],t:"Phrasal verbs"},
 {w:"put off",ipa:"/pʊt ɒf/",fr:"reporter",ex:"The meeting was put off until next week.",col:["put off a meeting","put off a decision"],t:"Phrasal verbs"},
 {w:"fill out",ipa:"/fɪl aʊt/",fr:"remplir (un formulaire)",ex:"Please fill out the application form.",col:["fill out a form","fill out an application"],t:"Phrasal verbs"},
 {w:"hand in",ipa:"/hænd ɪn/",fr:"remettre",ex:"Employees must hand in expense reports.",col:["hand in a report","hand in an application"],t:"Phrasal verbs"},
 {w:"follow up",ipa:"/ˈfɒləʊ ʌp/",fr:"faire un suivi",ex:"The sales team followed up with the client.",col:["follow up on a request","follow up with a customer"],t:"Phrasal verbs"},
 {w:"look into",ipa:"/lʊk ˈɪntuː/",fr:"examiner",ex:"Management will look into the complaint.",col:["look into a problem","look into an issue"],t:"Phrasal verbs"},
 {w:"turn down",ipa:"/tɜːn daʊn/",fr:"refuser",ex:"She turned down the job offer.",col:["turn down an offer","turn down a proposal"],t:"Phrasal verbs"},
 {w:"go over",ipa:"/ɡəʊ ˈəʊvə/",fr:"passer en revue",ex:"Let's go over the report together.",col:["go over a document","go over details"],t:"Phrasal verbs"},
 {w:"bring up",ipa:"/brɪŋ ʌp/",fr:"aborder un sujet",ex:"The issue was brought up during the meeting.",col:["bring up a concern","bring up an issue"],t:"Phrasal verbs"},
 {w:"call off",ipa:"/kɔːl ɒf/",fr:"annuler",ex:"The event was called off.",col:["call off a meeting","call off negotiations"],t:"Phrasal verbs"},
 {w:"find out",ipa:"/faɪnd aʊt/",fr:"découvrir",ex:"We found out about the delay yesterday.",col:["find out information","find out why"],t:"Phrasal verbs"},
 {w:"work out",ipa:"/wɜːk aʊt/",fr:"résoudre, fonctionner",ex:"We worked out a solution.",col:["work out a problem","work out details","⚠️ Peut aussi signifier \"faire du sport\"."],t:"Phrasal verbs"},
 {w:"point out",ipa:"/pɔɪnt aʊt/",fr:"signaler",ex:"The auditor pointed out several issues.",col:["point out a mistake","point out a problem"],t:"Phrasal verbs"},
 {w:"take on",ipa:"/teɪk ɒn/",fr:"prendre en charge",ex:"The department will take on new responsibilities.",col:["take on staff","take on a project"],t:"Phrasal verbs"},
 {w:"back up",ipa:"/bæk ʌp/",fr:"sauvegarder",ex:"Please back up all files.",col:["back up data","back up information"],t:"Phrasal verbs"},
 {w:"check in",ipa:"/tʃek ɪn/",fr:"s'enregistrer",ex:"Passengers must check in online.",col:["check in at a hotel","check in for a flight"],t:"Phrasal verbs"},
 {w:"check out",ipa:"/tʃek aʊt/",fr:"quitter / vérifier",ex:"Guests must check out by noon.",col:["check out of a hotel","check out a website"],t:"Phrasal verbs"},
 {w:"log in",ipa:"/lɒɡ ɪn/",fr:"se connecter",ex:"Users must log in to access the system.",col:["log in to an account","log in securely","TOEIC MASTER TABLE","Phrasal VerbMeaning"],t:"Phrasal verbs"},
 {w:"resume",ipa:"/\u02c8rez.\u0259.me\u026a/",fr:"CV",ex:"Please attach your resume to the form.",col:["update a resume","submit a resume"],t:"RH & recrutement"},
 {w:"purchase order",ipa:"/\u02c8p\u025c\u02d0.t\u0283\u0259s \u02cc\u0254\u02d0.d\u0259r/",fr:"bon de commande",ex:"The supplier received the purchase order yesterday.",col:["issue a purchase order"],t:"Logistique"},
 {w:"hand over",ipa:"/h\u00e6nd \u02c8\u0259\u028av\u0259/",fr:"remettre, transmettre",ex:"He handed over the documents.",col:["hand over responsibilities"],t:"Phrasal verbs"},
 {w:"deal with",ipa:"/di\u02d0l w\u026a\u00f0/",fr:"g\u00e9rer, traiter",ex:"Customer service deals with complaints.",col:["deal with a problem"],t:"Phrasal verbs"},
 {w:"come up with",ipa:"/k\u028cm \u028cp w\u026a\u00f0/",fr:"trouver (une id\u00e9e)",ex:"The team came up with a solution.",col:["come up with an idea"],t:"Phrasal verbs"},
 {w:"run out of",ipa:"/r\u028cn a\u028at \u0259v/",fr:"\u00eatre \u00e0 court de",ex:"The store ran out of stock.",col:["run out of time","run out of stock"],t:"Phrasal verbs"},
 {w:"pick up",ipa:"/p\u026ak \u028cp/",fr:"r\u00e9cup\u00e9rer",ex:"I will pick up the package.",col:["pick up an order"],t:"Phrasal verbs"},
 {w:"drop off",ipa:"/dr\u0252p \u0252f/",fr:"d\u00e9poser",ex:"The driver dropped off the goods.",col:["drop off a parcel"],t:"Phrasal verbs"},
 {w:"step down",ipa:"/step da\u028an/",fr:"d\u00e9missionner (d'un poste)",ex:"The CEO stepped down.",col:["step down as director"],t:"Phrasal verbs"},
 {w:"sign up for",ipa:"/sa\u026an \u028cp f\u0254\u02d0/",fr:"s'inscrire \u00e0",ex:"Staff signed up for workshops.",col:["sign up for a course"],t:"Phrasal verbs"},
 {w:"look forward to",ipa:"/l\u028ak \u02c8f\u0254\u02d0.w\u0259d tu\u02d0/",fr:"avoir h\u00e2te de",ex:"We look forward to hearing from you.",col:["look forward to your reply"],t:"Phrasal verbs"},
 {w:"get back to",ipa:"/\u0261et b\u00e6k tu\u02d0/",fr:"recontacter",ex:"We will get back to you soon.",col:["get back to a client"],t:"Phrasal verbs"},
 {w:"ambiguous",fr:"ambigu",ex:"The instructions were ambiguous.",t:"Vocabulaire avanc\u00e9"},
 {w:"benchmark",fr:"r\u00e9f\u00e9rence, \u00e9talon",ex:"The company became an industry benchmark.",t:"Vocabulaire avanc\u00e9"},
 {w:"compensate",fr:"compenser, indemniser",ex:"Employees were compensated for overtime.",t:"Vocabulaire avanc\u00e9"},
 {w:"confidential",fr:"confidentiel",ex:"This information is confidential.",t:"Vocabulaire avanc\u00e9"},
 {w:"constraint",fr:"contrainte",ex:"Budget constraints limited expansion.",t:"Vocabulaire avanc\u00e9"},
 {w:"deteriorate",fr:"se d\u00e9t\u00e9riorer",ex:"Market conditions deteriorated.",t:"Vocabulaire avanc\u00e9"},
 {w:"drawback",fr:"inconv\u00e9nient",ex:"One drawback is the high cost.",t:"Vocabulaire avanc\u00e9"},
 {w:"endorse",fr:"approuver, soutenir",ex:"The proposal was endorsed by management.",t:"Vocabulaire avanc\u00e9"},
 {w:"forecast",fr:"pr\u00e9vision ; pr\u00e9voir",ex:"Analysts forecast higher sales.",t:"Vocabulaire avanc\u00e9"},
 {w:"hinder",fr:"entraver",ex:"Delays hindered progress.",t:"Vocabulaire avanc\u00e9"},
 {w:"leverage",fr:"tirer parti de",ex:"We can leverage our experience.",t:"Vocabulaire avanc\u00e9"},
 {w:"offset",fr:"compenser",ex:"Savings offset increased costs.",t:"Vocabulaire avanc\u00e9"},
 {w:"outsource",fr:"externaliser",ex:"The company outsourced IT services.",t:"Vocabulaire avanc\u00e9"},
 {w:"redundancy",fr:"suppression de poste",ex:"Several redundancies were announced.",t:"Vocabulaire avanc\u00e9"},
 {w:"viable",fr:"viable",ex:"The proposal is financially viable.",t:"Vocabulaire avanc\u00e9"},
 {w:"alleviate",fr:"att\u00e9nuer",ex:"Measures alleviated concerns.",t:"Vocabulaire avanc\u00e9"},
 {w:"apparent",fr:"\u00e9vident",ex:"The problem became apparent.",t:"Vocabulaire avanc\u00e9"},
 {w:"backlog",fr:"arri\u00e9r\u00e9, retard accumul\u00e9",ex:"The company reduced its backlog.",t:"Vocabulaire avanc\u00e9"},
 {w:"compelling",fr:"convaincant",ex:"The report presents compelling evidence.",t:"Vocabulaire avanc\u00e9"},
 {w:"controversial",fr:"controvers\u00e9",ex:"The decision was controversial.",t:"Vocabulaire avanc\u00e9"},
 {w:"deficit",fr:"d\u00e9ficit",ex:"The budget showed a deficit.",t:"Vocabulaire avanc\u00e9"},
 {w:"surplus",fr:"exc\u00e9dent",ex:"The company reported a surplus.",t:"Vocabulaire avanc\u00e9"},
 {w:"diversify",fr:"diversifier",ex:"The company diversified its activities.",t:"Vocabulaire avanc\u00e9"},
 {w:"eliminate",fr:"supprimer",ex:"The company eliminated inefficiencies.",t:"Vocabulaire avanc\u00e9"},
 {w:"emerge",fr:"\u00e9merger, appara\u00eetre",ex:"New competitors emerged.",t:"Vocabulaire avanc\u00e9"},
 {w:"exclusive",fr:"exclusif",ex:"Exclusive benefits are offered.",t:"Vocabulaire avanc\u00e9"},
 {w:"franchise",fr:"franchise",ex:"The restaurant operates as a franchise.",t:"Vocabulaire avanc\u00e9"},
 {w:"implementation",fr:"mise en \u0153uvre",ex:"Implementation will begin next month.",t:"Vocabulaire avanc\u00e9"},
 {w:"inevitable",fr:"in\u00e9vitable",ex:"Some delays were inevitable.",t:"Vocabulaire avanc\u00e9"},
 {w:"innovative",fr:"innovant",ex:"The company launched an innovative product.",t:"Vocabulaire avanc\u00e9"},
 {w:"insight",fr:"analyse, \u00e9clairage",ex:"The survey provided valuable insights.",t:"Vocabulaire avanc\u00e9"},
 {w:"lucrative",fr:"lucratif",ex:"It was a lucrative contract.",t:"Vocabulaire avanc\u00e9"},
 {w:"minimise",fr:"minimiser",ex:"The goal is to minimise costs.",t:"Vocabulaire avanc\u00e9"},
 {w:"monopoly",fr:"monopole",ex:"The company held a monopoly.",t:"Vocabulaire avanc\u00e9"},
 {w:"obstacle",fr:"obstacle",ex:"Funding was a major obstacle.",t:"Vocabulaire avanc\u00e9"},
 {w:"optimise",fr:"optimiser",ex:"The software optimises performance.",t:"Vocabulaire avanc\u00e9"},
 {w:"prestigious",fr:"prestigieux",ex:"She works for a prestigious firm.",t:"Vocabulaire avanc\u00e9"},
 {w:"sustainable",fr:"durable",ex:"The company adopted sustainable practices.",t:"Vocabulaire avanc\u00e9"},
 {w:"compliance",fr:"conformit\u00e9 (r\u00e9glementaire)",ex:"The company remains fully compliant.",t:"Vocabulaire avanc\u00e9"},
 {w:"stakeholder",fr:"partie prenante",ex:"All stakeholders were consulted.",t:"Vocabulaire avanc\u00e9"},
 {w:"turnover",fr:"rotation du personnel ; chiffre d'affaires",ex:"Employee turnover has decreased.",t:"Vocabulaire avanc\u00e9"},
 {w:"streamline",fr:"rationaliser",ex:"The company streamlined its operations.",t:"Vocabulaire avanc\u00e9"},
 {w:"waiver",fr:"renonciation, d\u00e9rogation",ex:"Participants signed a waiver.",t:"Vocabulaire avanc\u00e9"},
 {w:"agenda",ipa:"/əˈdʒen.də/",fr:"ordre du jour",ex:"Please review the agenda before the meeting.",col:["meeting agenda","agenda item"],t:"Bureau & réunions"},
 {w:"minutes",ipa:"/ˈmɪn.ɪts/",fr:"compte rendu (de réunion)",ex:"The secretary took the minutes.",col:["meeting minutes","take the minutes"],t:"Bureau & réunions"},
 {w:"venue",ipa:"/ˈven.juː/",fr:"lieu (d'un événement)",ex:"The venue was changed at the last minute.",col:["conference venue","change the venue"],t:"Bureau & réunions"},
 {w:"adjourn",ipa:"/əˈdʒɜːn/",fr:"lever la séance",ex:"The meeting was adjourned until Monday.",col:["adjourn a meeting"],t:"Bureau & réunions"},
 {w:"keynote",ipa:"/ˈkiː.nəʊt/",fr:"discours principal",ex:"She gave the keynote speech.",col:["keynote speaker","keynote address"],t:"Bureau & réunions"},
 {w:"handout",ipa:"/ˈhænd.aʊt/",fr:"document distribué",ex:"Handouts were given to all participants.",col:["distribute handouts"],t:"Bureau & réunions"},
 {w:"attendee",ipa:"/əˌtenˈdiː/",fr:"participant·e",ex:"All attendees received a badge.",col:["conference attendee"],t:"Bureau & réunions"},
 {w:"schedule",ipa:"/ˈʃed.juːl/",fr:"planning, emploi du temps",ex:"The schedule is very tight this week.",col:["busy schedule","ahead of schedule"],t:"Bureau & réunions"},
 {w:"postpone",ipa:"/pəˈspəʊn/",fr:"reporter",ex:"The launch was postponed.",col:["postpone a meeting","postpone a decision"],t:"Bureau & réunions"},
 {w:"chair",ipa:"/tʃeər/",fr:"présider",ex:"She chaired the committee.",col:["chair a meeting"],t:"Bureau & réunions"},
 {w:"itinerary",ipa:"/aɪˈtɪn.ər.ər.i/",fr:"itinéraire",ex:"The travel itinerary was sent by email.",col:["travel itinerary"],t:"Voyages d'affaires"},
 {w:"boarding pass",ipa:"/ˈbɔː.dɪŋ pɑːs/",fr:"carte d'embarquement",ex:"Please have your boarding pass ready.",col:["print a boarding pass"],t:"Voyages d'affaires"},
 {w:"layover",ipa:"/ˈleɪˌəʊ.vər/",fr:"escale",ex:"There is a two-hour layover in Frankfurt.",col:["short layover"],t:"Voyages d'affaires"},
 {w:"reimbursement",ipa:"/ˌriː.ɪmˈbɜːs.mənt/",fr:"remboursement (de frais)",ex:"Submit receipts for reimbursement.",col:["expense reimbursement"],t:"Voyages d'affaires"},
 {w:"accommodation",ipa:"/əˌkɒm.əˈdeɪ.ʃən/",fr:"hébergement",ex:"Accommodation is provided for staff.",col:["hotel accommodation"],t:"Voyages d'affaires"},
 {w:"fare",ipa:"/feər/",fr:"tarif (transport)",ex:"The train fare increased.",col:["train fare","airfare"],t:"Voyages d'affaires"},
 {w:"reservation",ipa:"/ˌrez.əˈveɪ.ʃən/",fr:"réservation",ex:"I would like to make a reservation.",col:["hotel reservation","cancel a reservation"],t:"Voyages d'affaires"},
 {w:"departure",ipa:"/dɪˈpɑː.tʃər/",fr:"départ",ex:"The departure was delayed.",col:["departure time","departure gate"],t:"Voyages d'affaires"},
 {w:"luggage",ipa:"/ˈlʌɡ.ɪdʒ/",fr:"bagages",ex:"Please collect your luggage.",col:["hand luggage","luggage allowance"],t:"Voyages d'affaires"},
 {w:"brand",ipa:"/brænd/",fr:"marque",ex:"The brand is well known.",col:["brand awareness","brand image"],t:"Marketing & ventes"},
 {w:"campaign",ipa:"/kæmˈpeɪn/",fr:"campagne",ex:"The advertising campaign was successful.",col:["marketing campaign","launch a campaign"],t:"Marketing & ventes"},
 {w:"discount",ipa:"/ˈdɪs.kaʊnt/",fr:"remise, réduction",ex:"Customers receive a 10% discount.",col:["offer a discount","discount price"],t:"Marketing & ventes"},
 {w:"retail",ipa:"/ˈriː.teɪl/",fr:"vente au détail",ex:"The product is sold at retail price.",col:["retail store","retail price"],t:"Marketing & ventes"},
 {w:"wholesale",ipa:"/ˈhəʊl.seɪl/",fr:"vente en gros",ex:"They buy at wholesale prices.",col:["wholesale price"],t:"Marketing & ventes"},
 {w:"launch",ipa:"/lɔːntʃ/",fr:"lancement ; lancer",ex:"The product launch is next month.",col:["product launch","launch date"],t:"Marketing & ventes"},
 {w:"quota",ipa:"/ˈkwəʊ.tə/",fr:"quota, objectif",ex:"The sales team met its quota.",col:["sales quota","meet a quota"],t:"Marketing & ventes"},
 {w:"target market",ipa:"/ˈtɑː.ɡɪt ˈmɑː.kɪt/",fr:"marché cible",ex:"Young adults are our target market.",col:["identify a target market"],t:"Marketing & ventes"},
 {w:"market share",ipa:"/ˈmɑː.kɪt ʃeər/",fr:"part de marché",ex:"The company gained market share.",col:["increase market share"],t:"Marketing & ventes"},
 {w:"software",ipa:"/ˈsɒft.weər/",fr:"logiciel",ex:"The software needs an update.",col:["software update","accounting software"],t:"Technologie"},
 {w:"hardware",ipa:"/ˈhɑːd.weər/",fr:"matériel informatique",ex:"The hardware is outdated.",col:["computer hardware"],t:"Technologie"},
 {w:"upgrade",ipa:"/ˈʌp.ɡreɪd/",fr:"mise à niveau",ex:"We upgraded the system.",col:["software upgrade","upgrade a plan"],t:"Technologie"},
 {w:"password",ipa:"/ˈpɑːs.wɜːd/",fr:"mot de passe",ex:"Please reset your password.",col:["strong password","reset a password"],t:"Technologie"},
 {w:"database",ipa:"/ˈdeɪ.tə.beɪs/",fr:"base de données",ex:"Customer data is stored in a database.",col:["customer database","update a database"],t:"Technologie"},
 {w:"downtime",ipa:"/ˈdaʊn.taɪm/",fr:"temps d'arrêt",ex:"The maintenance caused some downtime.",col:["server downtime","scheduled downtime"],t:"Technologie"},
 {w:"breakdown",ipa:"/ˈbreɪk.daʊn/",fr:"panne",ex:"A breakdown delayed production.",col:["equipment breakdown"],t:"Technologie"},
 {w:"install",ipa:"/ɪnˈstɔːl/",fr:"installer",ex:"Please install the latest version.",col:["install software"],t:"Technologie"},
 {w:"defect",ipa:"/ˈdiː.fekt/",fr:"défaut",ex:"The product had a defect.",col:["manufacturing defect","defect rate"],t:"Production & qualité"},
 {w:"quality control",ipa:"/ˈkwɒl.ə.ti kənˈtrəʊl/",fr:"contrôle qualité",ex:"Quality control rejected the batch.",col:["quality control check"],t:"Production & qualité"},
 {w:"maintenance",ipa:"/ˈmeɪn.tən.əns/",fr:"entretien, maintenance",ex:"Regular maintenance is required.",col:["routine maintenance","maintenance costs"],t:"Production & qualité"},
 {w:"manufacturer",ipa:"/ˌmæn.jəˈfæk.tʃər.ər/",fr:"fabricant",ex:"The manufacturer issued a recall.",col:["leading manufacturer"],t:"Production & qualité"},
 {w:"warranty",ipa:"/ˈwɒr.ən.ti/",fr:"garantie",ex:"The product comes with a warranty.",col:["under warranty","extend a warranty"],t:"Production & qualité"},
 {w:"recall",ipa:"/rɪˈkɔːl/",fr:"rappel (produit)",ex:"The company issued a product recall.",col:["product recall","issue a recall"],t:"Production & qualité"},
 {w:"output",ipa:"/ˈaʊt.pʊt/",fr:"production, rendement",ex:"Output increased this quarter.",col:["increase output","production output"],t:"Production & qualité"},
 {w:"specification",ipa:"/ˌspes.ɪ.fɪˈkeɪ.ʃən/",fr:"cahier des charges, spécification",ex:"The product meets all specifications.",col:["technical specifications"],t:"Production & qualité"},
 {w:"contract",ipa:"/ˈkɒn.trækt/",fr:"contrat",ex:"Both parties signed the contract.",col:["sign a contract","contract terms"],t:"Droit & contrats"},
 {w:"clause",ipa:"/klɔːz/",fr:"clause",ex:"The contract contains a confidentiality clause.",col:["contract clause"],t:"Droit & contrats"},
 {w:"agreement",ipa:"/əˈɡriː.mənt/",fr:"accord",ex:"They reached an agreement.",col:["reach an agreement","trade agreement"],t:"Droit & contrats"},
 {w:"breach",ipa:"/briːtʃ/",fr:"rupture, violation",ex:"This is a breach of contract.",col:["breach of contract"],t:"Droit & contrats"},
 {w:"liable",ipa:"/ˈlaɪ.ə.bəl/",fr:"responsable (juridiquement)",ex:"The company is liable for damages.",col:["liable for damages"],t:"Droit & contrats"},
 {w:"terminate",ipa:"/ˈtɜː.mɪ.neɪt/",fr:"résilier, mettre fin à",ex:"Either party may terminate the agreement.",col:["terminate a contract"],t:"Droit & contrats"},
 {w:"renew",ipa:"/rɪˈnjuː/",fr:"renouveler",ex:"We renewed the contract for a year.",col:["renew a contract","renew a subscription"],t:"Droit & contrats"},
 {w:"amendment",ipa:"/əˈmend.mənt/",fr:"avenant, modification",ex:"An amendment was added to the contract.",col:["make an amendment"],t:"Droit & contrats"},
 {w:"obligation",ipa:"/ˌɒb.lɪˈɡeɪ.ʃən/",fr:"obligation",ex:"Both sides met their obligations.",col:["legal obligation","meet an obligation"],t:"Droit & contrats"},
 {w:"valid",ipa:"/ˈvæl.ɪd/",fr:"valable, valide",ex:"The offer is valid until Friday.",col:["valid until","valid contract"],t:"Droit & contrats"},
 {w:"feedback",ipa:"/ˈfiːd.bæk/",fr:"retour, avis",ex:"We welcome customer feedback.",col:["customer feedback","positive feedback"],t:"Service client"},
 {w:"loyalty",ipa:"/ˈlɔɪ.əl.ti/",fr:"fidélité",ex:"The program rewards customer loyalty.",col:["customer loyalty","loyalty program"],t:"Service client"},
 {w:"assistance",ipa:"/əˈsɪs.təns/",fr:"aide, assistance",ex:"Thank you for your assistance.",col:["technical assistance","provide assistance"],t:"Service client"},
 {w:"representative",ipa:"/ˌrep.rɪˈzen.tə.tɪv/",fr:"représentant·e",ex:"A sales representative will call you.",col:["sales representative","customer representative"],t:"Service client"},
 {w:"resolve",ipa:"/rɪˈzɒlv/",fr:"résoudre",ex:"We resolved the issue quickly.",col:["resolve an issue","resolve a complaint"],t:"Service client"},
 {w:"satisfaction",ipa:"/ˌsæt.ɪsˈfæk.ʃən/",fr:"satisfaction",ex:"Customer satisfaction is our priority.",col:["customer satisfaction"],t:"Service client"},
 {w:"courteous",ipa:"/ˈkɜː.ti.əs/",fr:"courtois, poli",ex:"The staff were very courteous.",col:["courteous service"],t:"Service client"},
 {w:"emissions",ipa:"/ɪˈmɪʃ.ənz/",fr:"émissions",ex:"The company reduced its emissions.",col:["carbon emissions","reduce emissions"],t:"Environnement & RSE"},
 {w:"waste",ipa:"/weɪst/",fr:"déchets ; gaspiller",ex:"The factory reduced its waste.",col:["waste management","reduce waste"],t:"Environnement & RSE"},
 {w:"recycling",ipa:"/ˌriːˈsaɪ.klɪŋ/",fr:"recyclage",ex:"The office introduced a recycling program.",col:["recycling program"],t:"Environnement & RSE"},
 {w:"renewable",ipa:"/rɪˈnjuː.ə.bəl/",fr:"renouvelable",ex:"They invested in renewable energy.",col:["renewable energy"],t:"Environnement & RSE"},
 {w:"carbon footprint",ipa:"/ˈkɑː.bən ˈfʊt.prɪnt/",fr:"empreinte carbone",ex:"We aim to reduce our carbon footprint.",col:["reduce a carbon footprint"],t:"Environnement & RSE"},
 {w:"conservation",ipa:"/ˌkɒn.səˈveɪ.ʃən/",fr:"préservation, économie",ex:"Energy conservation saves money.",col:["energy conservation"],t:"Environnement & RSE"},
 {w:"premises",ipa:"/ˈprem.ɪs.ɪz/",fr:"locaux",ex:"Smoking is not allowed on the premises.",col:["business premises","on the premises"],t:"Immobilier & locaux"},
 {w:"lease",ipa:"/liːs/",fr:"bail ; louer",ex:"The company signed a five-year lease.",col:["sign a lease","commercial lease"],t:"Immobilier & locaux"},
 {w:"tenant",ipa:"/ˈten.ənt/",fr:"locataire",ex:"The tenant pays rent monthly.",col:["commercial tenant"],t:"Immobilier & locaux"},
 {w:"rent",ipa:"/rent/",fr:"loyer ; louer",ex:"The monthly rent increased.",col:["pay rent","rent an office"],t:"Immobilier & locaux"},
 {w:"facility",ipa:"/fəˈsɪl.ə.ti/",fr:"installation, établissement",ex:"The new facility opens in June.",col:["production facility","sports facility"],t:"Immobilier & locaux"},
 {w:"relocate",ipa:"/ˌriːˈləʊ.keɪt/",fr:"déménager (une entreprise)",ex:"The company relocated to Lyon.",col:["relocate offices"],t:"Immobilier & locaux"},
 {w:"safety",ipa:"/ˈseɪf.ti/",fr:"sécurité",ex:"Safety is everyone's responsibility.",col:["safety regulations","workplace safety"],t:"Santé & sécurité"},
 {w:"hazard",ipa:"/ˈhæz.əd/",fr:"danger, risque",ex:"Report any safety hazard.",col:["fire hazard","health hazard"],t:"Santé & sécurité"},
 {w:"precaution",ipa:"/prɪˈkɔː.ʃən/",fr:"précaution",ex:"Take all necessary precautions.",col:["safety precaution","take precautions"],t:"Santé & sécurité"},
 {w:"emergency",ipa:"/ɪˈmɜː.dʒən.si/",fr:"urgence",ex:"Know the emergency exits.",col:["emergency exit","emergency procedure"],t:"Santé & sécurité"},
 {w:"evacuation",ipa:"/ɪˌvæk.juˈeɪ.ʃən/",fr:"évacuation",ex:"An evacuation drill is scheduled.",col:["evacuation plan"],t:"Santé & sécurité"},
 {w:"injury",ipa:"/ˈɪn.dʒər.i/",fr:"blessure",ex:"Report any workplace injury.",col:["workplace injury","prevent injury"],t:"Santé & sécurité"},
 {w:"regulation",ipa:"/ˌreɡ.jəˈleɪ.ʃən/",fr:"réglementation",ex:"New safety regulations apply.",col:["safety regulations","comply with regulations"],t:"Santé & sécurité"},
 {w:"inspection",ipa:"/ɪnˈspek.ʃən/",fr:"inspection, contrôle",ex:"The facility passed inspection.",col:["safety inspection","routine inspection"],t:"Santé & sécurité"},
 {w:"implement",ipa:"/ˈɪm.plɪ.ment/",fr:"mettre en œuvre",ex:"We implemented a new policy.",col:["implement a policy","implement changes"],t:"Verbes fréquents"},
 {w:"ensure",ipa:"/ɪnˈʃɔːr/",fr:"garantir, s'assurer",ex:"Please ensure all forms are signed.",col:["ensure quality","ensure compliance"],t:"Verbes fréquents"},
 {w:"provide",ipa:"/prəˈvaɪd/",fr:"fournir",ex:"We provide training to new staff.",col:["provide support","provide information"],t:"Verbes fréquents"},
 {w:"obtain",ipa:"/əbˈteɪn/",fr:"obtenir",ex:"You must obtain approval first.",col:["obtain approval","obtain a licence"],t:"Verbes fréquents"},
 {w:"maintain",ipa:"/meɪnˈteɪn/",fr:"maintenir, entretenir",ex:"We maintain high standards.",col:["maintain equipment","maintain standards"],t:"Verbes fréquents"},
 {w:"conduct",ipa:"/kənˈdʌkt/",fr:"mener, réaliser",ex:"We conducted a survey.",col:["conduct research","conduct an interview"],t:"Verbes fréquents"},
 {w:"submit",ipa:"/səbˈmɪt/",fr:"soumettre, remettre",ex:"Please submit your application online.",col:["submit a report","submit a request"],t:"Verbes fréquents"},
 {w:"approve",ipa:"/əˈpruːv/",fr:"approuver",ex:"The budget was approved.",col:["approve a request","approve a budget"],t:"Verbes fréquents"},
 {w:"exceed",ipa:"/ɪkˈsiːd/",fr:"dépasser",ex:"Sales exceeded expectations.",col:["exceed expectations","exceed a limit"],t:"Verbes fréquents"},
 {w:"negotiate",ipa:"/nɪˈɡəʊ.ʃi.eɪt/",fr:"négocier",ex:"They negotiated a better price.",col:["negotiate a contract","negotiate terms"],t:"Verbes fréquents"},
 {w:"purchase",ipa:"/ˈpɜː.tʃəs/",fr:"acheter ; achat",ex:"The company purchased new equipment.",col:["purchase order","make a purchase"],t:"Verbes fréquents"},
 {w:"distribute",ipa:"/dɪˈstrɪb.juːt/",fr:"distribuer",ex:"Brochures were distributed to clients.",col:["distribute documents"],t:"Verbes fréquents"},
 {w:"approximately",ipa:"/əˈprɒk.sɪ.mət.li/",fr:"environ, approximativement",ex:"The flight takes approximately two hours.",col:["approximately equal"],t:"Adverbes & adjectifs"},
 {w:"recently",ipa:"/ˈriːsnt.li/",fr:"récemment",ex:"The policy was recently updated.",col:["recently hired"],t:"Adverbes & adjectifs"},
 {w:"temporarily",ipa:"/ˈtem.pər.ər.ə.li/",fr:"temporairement",ex:"The service is temporarily unavailable.",col:["temporarily closed"],t:"Adverbes & adjectifs"},
 {w:"significantly",ipa:"/sɪɡˈnɪf.ɪ.kənt.li/",fr:"de façon significative",ex:"Sales increased significantly.",col:["significantly higher"],t:"Adverbes & adjectifs"},
 {w:"eligible",ipa:"/ˈel.ɪ.dʒə.bəl/",fr:"admissible, éligible",ex:"Employees are eligible for a bonus.",col:["eligible for","eligible candidate"],t:"Adverbes & adjectifs"},
 {w:"prompt",ipa:"/prɒmpt/",fr:"rapide, ponctuel",ex:"Thank you for your prompt reply.",col:["prompt response","prompt payment"],t:"Adverbes & adjectifs"},
 {w:"reasonable",ipa:"/ˈriː.zən.ə.bəl/",fr:"raisonnable",ex:"The price is reasonable.",col:["reasonable price","reasonable request"],t:"Adverbes & adjectifs"},
 {w:"sufficient",ipa:"/səˈfɪʃ.ənt/",fr:"suffisant",ex:"We have sufficient supplies.",col:["sufficient funds","sufficient time"],t:"Adverbes & adjectifs"},
 {w:"reluctant",ipa:"/rɪˈlʌk.tənt/",fr:"réticent",ex:"Customers were reluctant to change.",col:["reluctant to accept"],t:"Adverbes & adjectifs"},
 {w:"willing",ipa:"/ˈwɪl.ɪŋ/",fr:"disposé, prêt à",ex:"She is willing to relocate.",col:["willing to help"],t:"Adverbes & adjectifs"}
];
window.TOEIC_BANK.QUESTIONS = [
 {id:"A01-001",dom:"Grammaire",skill:"Subject-Verb Agreement",stem:"The manager ____ responsible for the project.",opts:["are","were","is","have been"],a:2,why:"« Manager » est un sujet singulier → verbe singulier → is.",dx:{0:{t:"forme",note:"« are » est un pluriel : il ne s'accorde pas avec le sujet singulier *the manager*."},1:{t:"temps",note:"« were » introduit un passe non justifie (et reste un pluriel) : ni le temps ni l'accord ne collent."},3:{t:"temps",note:"« have been » impose un present perfect inutile ici : un present simple suffit."}}},
 {id:"A01-003",dom:"Grammaire",skill:"Subject-Verb Agreement",stem:"The list of applicants ____ available online.",opts:["are","were","have","is"],a:3,why:"Le sujet est « the list » (singulier), pas « applicants » → is."},
 {id:"A03-001",dom:"Grammaire",skill:"Each / Every",stem:"Each employee ____ a company badge.",opts:["have","has","are having","having"],a:1,why:"« Each » est singulier → has."},
 {id:"A05-002",dom:"Grammaire",skill:"The number of",stem:"The number of complaints ____ increasing.",opts:["are","were","have been","is"],a:3,why:"« The number of… » prend un verbe singulier → is."},
 {id:"B01-001",dom:"Grammaire",skill:"Gérondif après préposition",stem:"Thank you for ____ the meeting.",opts:["attend","attended","attending","attends"],a:2,why:"Après une préposition (for), on utilise le gérondif → attending."},
 {id:"B05-001",dom:"Grammaire",skill:"Infinitif après decide",stem:"The company decided ____ a new supplier.",opts:["hire","hiring","to hire","hired"],a:2,why:"« decide » est suivi de l'infinitif → to hire."},
 {id:"C01-001",dom:"Grammaire",skill:"Voix passive",stem:"The report ____ yesterday.",opts:["submitted","was submitted","submitting","has submit"],a:1,why:"Action subie au passé → was submitted."},
 {id:"C02-001",dom:"Grammaire",skill:"Modal passif",stem:"The form must ____ before Friday.",opts:["complete","completed","be completed","be complete"],a:2,why:"Après un modal, passif = be + participe → be completed."},
 {id:"D03-001",dom:"Connecteurs",skill:"By vs Until",stem:"Please submit your application ____ Friday.",opts:["until","during","by","since"],a:2,why:"« by » = au plus tard (date limite) ; « until » = jusqu'à."},
 {id:"D05-001",dom:"Connecteurs",skill:"Despite vs Although",stem:"____ the delay, the project was completed.",opts:["Although","Despite","Because","While"],a:1,why:"« Despite » est suivi d'un nom → Despite the delay."},
 {id:"D06-001",dom:"Connecteurs",skill:"Because vs Because of",stem:"The flight was cancelled ____ bad weather.",opts:["because","although","because of","while"],a:2,why:"« because of » + nom ; « because » + sujet et verbe."},
 {id:"E04-001",dom:"Collocations",skill:"Meetings",stem:"The board will ____ a meeting next week.",opts:["hold","catch","realise","support"],a:0,why:"Collocation correcte : hold a meeting."},
 {id:"E08-001",dom:"Collocations",skill:"Logistique",stem:"The shipment arrived ahead of ____.",opts:["planning","schedule","organisation","programme"],a:1,why:"Expression figée : ahead of schedule (en avance)."},
 {id:"E09-001",dom:"Collocations",skill:"Service client",stem:"A customer submitted a ____.",opts:["complaint","accusation","dissatisfaction","regret"],a:0,why:"On dit submit/file a complaint."},
 {id:"E10-001",dom:"Collocations",skill:"Décisions",stem:"The committee will ____ a decision after the review.",opts:["take","make","do","give"],a:1,why:"On dit make a decision (et non « do/give a decision »)."},
 {id:"E10-002",dom:"Collocations",skill:"Responsabilité",stem:"Managers must ____ responsibility for their teams.",opts:["make","take","do","hold"],a:1,why:"take responsibility = assumer la responsabilité."},
 {id:"E11-001",dom:"Collocations",skill:"Délais",stem:"The team worked overtime to ____ the deadline.",opts:["reach","catch","meet","arrive"],a:2,why:"meet a deadline = respecter un délai."},
 {id:"E11-002",dom:"Collocations",skill:"Négociation",stem:"After long talks, both sides ____ an agreement.",opts:["reached","made","arrived","did"],a:0,why:"reach an agreement = parvenir à un accord."},
 {id:"E12-001",dom:"Collocations",skill:"Commandes",stem:"The customer would like to ____ an order for 200 units.",opts:["make","do","place","put"],a:2,why:"place an order = passer une commande."},
 {id:"E12-002",dom:"Collocations",skill:"Communication",stem:"The campaign aims to ____ awareness of the new policy.",opts:["grow","raise","rise","lift"],a:1,why:"raise awareness = sensibiliser (rise est intransitif)."},
 {id:"E13-001",dom:"Collocations",skill:"Études de marché",stem:"The marketing team will ____ a survey among clients.",opts:["make","do","conduct","pass"],a:2,why:"conduct a survey = mener une enquête."},
 {id:"E13-002",dom:"Collocations",skill:"Produits",stem:"The company plans to ____ a new product next quarter.",opts:["raise","launch","throw","lift"],a:1,why:"launch a product = lancer un produit."},
 {id:"E14-001",dom:"Collocations",skill:"Clientèle",stem:"Lower prices help ____ new customers.",opts:["call","attract","invite","gather"],a:1,why:"attract customers = attirer des clients."},
 {id:"E14-002",dom:"Collocations",skill:"Service client",stem:"Staff are trained to ____ complaints professionally.",opts:["hold","make","handle","take"],a:2,why:"handle a complaint = traiter une réclamation."},
 {id:"E15-001",dom:"Collocations",skill:"Événements",stem:"Over 300 delegates will ____ the annual conference.",opts:["assist","attend","participate","join"],a:1,why:"attend a conference = assister à une conférence (assist = aider)."},
 {id:"E15-002",dom:"Collocations",skill:"Présentations",stem:"She will ____ a presentation to the board on Monday.",opts:["tell","say","give","speak"],a:2,why:"give a presentation = faire une présentation."},
 {id:"E16-001",dom:"Collocations",skill:"Contrats",stem:"Both parties are ready to ____ the contract.",opts:["subscribe","sign","write","firm"],a:1,why:"sign a contract = signer un contrat."},
 {id:"E16-002",dom:"Collocations",skill:"Recrutement",stem:"We need to ____ the vacant position quickly.",opts:["complete","occupy","fill","take"],a:2,why:"fill a position = pourvoir un poste."},
 {id:"E17-001",dom:"Collocations",skill:"Ventes",stem:"The promotion is designed to ____ sales.",opts:["boost","grow up","raise up","high"],a:0,why:"boost sales = doper les ventes."},
 {id:"E17-002",dom:"Collocations",skill:"Coûts",stem:"The new process will help the firm ____ costs.",opts:["lower down","cut","decrease down","short"],a:1,why:"cut costs = réduire les coûts."},
 {id:"E18-001",dom:"Collocations",skill:"Adjectif + nom",stem:"Allow extra travel time because of ____ traffic.",opts:["strong","big","heavy","large"],a:2,why:"heavy traffic = circulation dense."},
 {id:"E18-002",dom:"Collocations",skill:"Adjectif + nom",stem:"Our company offers ____ prices to stay ahead.",opts:["competitive","concurrent","competing","rival"],a:0,why:"competitive prices = prix compétitifs."},
 {id:"E18-003",dom:"Collocations",skill:"Adjectif + nom",stem:"Make sure your passport is ____ before travelling.",opts:["valuable","valid","available","value"],a:1,why:"a valid passport = un passeport en cours de validité."},
 {id:"E18-004",dom:"Collocations",skill:"Adjectif + nom",stem:"We are working to a very ____ schedule this month.",opts:["narrow","close","tight","strict"],a:2,why:"a tight schedule = un emploi du temps serré."},
 {id:"E19-001",dom:"Collocations",skill:"Expressions figées",stem:"Please confirm your attendance ____ advance.",opts:["on","at","in","by"],a:2,why:"in advance = à l'avance."},
 {id:"E19-002",dom:"Collocations",skill:"Expressions figées",stem:"Mr. Diaz is ____ charge of the logistics team.",opts:["on","in","at","under"],a:1,why:"in charge of = responsable de."},
 {id:"E19-003",dom:"Collocations",skill:"Expressions figées",stem:"I'm writing ____ behalf of the marketing department.",opts:["in","on","at","by"],a:1,why:"on behalf of = au nom de."},
 {id:"E19-004",dom:"Collocations",skill:"Expressions figées",stem:"The delivery arrived right ____ schedule.",opts:["in","on","at","to"],a:1,why:"on schedule = dans les temps."},
 {id:"E20-001",dom:"Collocations",skill:"Réunions",stem:"Could you ____ the minutes during the meeting?",opts:["make","take","do","write"],a:1,why:"take the minutes = rédiger le compte rendu."},
 {id:"E20-002",dom:"Collocations",skill:"Finance",stem:"The startup managed to ____ funds from investors.",opts:["rise","gain","raise","win"],a:2,why:"raise funds = lever des fonds."},
 {id:"E20-003",dom:"Collocations",skill:"Objectifs",stem:"The sales team easily ____ their targets this year.",opts:["reached up","met","arrived","gained"],a:1,why:"meet a target = atteindre un objectif."},
 {id:"E20-004",dom:"Collocations",skill:"Rendez-vous",stem:"I'd like to ____ an appointment with Dr. Khan.",opts:["take","make","do","give"],a:1,why:"make an appointment = prendre rendez-vous."},
 {id:"F04-001",dom:"Phrasal verbs",skill:"Put off",stem:"The meeting was ____ until next week.",opts:["carried out","put off","looked into","set up"],a:1,why:"put off = reporter."},
 {id:"F05-001",dom:"Phrasal verbs",skill:"Call off",stem:"The conference was ____ due to bad weather.",opts:["backed up","called off","filled out","logged in"],a:1,why:"call off = annuler."},
 {id:"F06-001",dom:"Phrasal verbs",skill:"Carry out",stem:"The engineers will ____ a series of safety tests.",opts:["carry out","put off","look into","set up"],a:0,why:"carry out = effectuer, réaliser (une tâche, un test)."},
 {id:"F07-001",dom:"Phrasal verbs",skill:"Set up",stem:"IT will ____ your new account this afternoon.",opts:["fill out","set up","take over","hand in"],a:1,why:"set up = créer, configurer, mettre en place."},
 {id:"F08-001",dom:"Phrasal verbs",skill:"Fill out",stem:"Please ____ this form before the interview.",opts:["bring up","back up","fill out","run out"],a:2,why:"fill out (a form) = remplir un formulaire."},
 {id:"F09-001",dom:"Phrasal verbs",skill:"Look into",stem:"We will ____ the complaint and reply within 48 hours.",opts:["look into","put off","call off","take off"],a:0,why:"look into = examiner, enquêter sur."},
 {id:"F10-001",dom:"Phrasal verbs",skill:"Turn down",stem:"She had to ____ the job offer because of the location.",opts:["hand out","turn down","set up","log in"],a:1,why:"turn down = refuser, décliner."},
 {id:"F11-001",dom:"Phrasal verbs",skill:"Take over",stem:"A larger firm will ____ the company next year.",opts:["take off","look into","take over","carry out"],a:2,why:"take over = reprendre, racheter (une entreprise)."},
 {id:"F12-001",dom:"Phrasal verbs",skill:"Lay off",stem:"The factory had to ____ 50 workers after the merger.",opts:["lay off","hand in","back up","go over"],a:0,why:"lay off = licencier (pour raisons économiques)."},
 {id:"F13-001",dom:"Phrasal verbs",skill:"Hand in",stem:"Trainees must ____ their reports by Friday.",opts:["hand out","hand in","run out","check in"],a:1,why:"hand in = rendre, remettre (un document)."},
 {id:"F14-001",dom:"Phrasal verbs",skill:"Hand out",stem:"Volunteers will ____ brochures at the entrance.",opts:["bring up","fill out","hand out","sign up"],a:2,why:"hand out = distribuer."},
 {id:"F15-001",dom:"Phrasal verbs",skill:"Run out of",stem:"The office has ____ printer paper again.",opts:["run out of","cut back on","catch up on","put up with"],a:0,why:"run out of = être à court de, manquer de."},
 {id:"F16-001",dom:"Phrasal verbs",skill:"Go over",stem:"Let's ____ the figures one more time before the meeting.",opts:["come up with","go over","drop off","take off"],a:1,why:"go over = passer en revue, revoir."},
 {id:"F17-001",dom:"Phrasal verbs",skill:"Bring up",stem:"She ____ an important point during the discussion.",opts:["set up","brought up","filled out","logged in"],a:1,why:"bring up = soulever (un sujet, un point)."},
 {id:"F18-001",dom:"Phrasal verbs",skill:"Back up",stem:"Always ____ your files before updating the system.",opts:["back up","check out","turn down","carry out"],a:0,why:"back up = sauvegarder."},
 {id:"F19-001",dom:"Phrasal verbs",skill:"Drop off",stem:"Could you ____ these documents at reception?",opts:["pick up","drop off","run out","go over"],a:1,why:"drop off = déposer (quelque chose quelque part)."},
 {id:"F20-001",dom:"Phrasal verbs",skill:"Pick up",stem:"I'll ____ the visitors from the airport at noon.",opts:["bring up","fill out","pick up","hand in"],a:2,why:"pick up = aller chercher, récupérer (quelqu'un/quelque chose)."},
 {id:"F21-001",dom:"Phrasal verbs",skill:"Check in",stem:"Guests can ____ at the hotel after 3 p.m.",opts:["check in","take over","lay off","look into"],a:0,why:"check in = s'enregistrer (hôtel, aéroport)."},
 {id:"F22-001",dom:"Phrasal verbs",skill:"Get back to",stem:"I'll ____ you as soon as I have the details.",opts:["catch up on","get back to","put up with","cut back on"],a:1,why:"get back to (someone) = recontacter, répondre à quelqu'un."},
 {id:"F23-001",dom:"Phrasal verbs",skill:"Catch up on",stem:"After the holidays, I need to ____ my emails.",opts:["come up with","sign up for","catch up on","turn down"],a:2,why:"catch up on = rattraper (du retard sur)."},
 {id:"F24-001",dom:"Phrasal verbs",skill:"Cut back on",stem:"To save money, the firm decided to ____ travel expenses.",opts:["cut back on","carry out","hand out","set up"],a:0,why:"cut back on = réduire, diminuer (des dépenses)."},
 {id:"F25-001",dom:"Phrasal verbs",skill:"Come up with",stem:"The team needs to ____ a new marketing strategy.",opts:["go over","come up with","drop off","check in"],a:1,why:"come up with = trouver, proposer (une idée)."},
 {id:"F26-001",dom:"Phrasal verbs",skill:"Point out",stem:"The auditor ____ several errors in the report.",opts:["handed in","backed up","pointed out","ran out"],a:2,why:"point out = signaler, faire remarquer."},
 {id:"F27-001",dom:"Phrasal verbs",skill:"Sort out",stem:"Could you ____ this billing issue for the client?",opts:["sort out","take off","bring up","sign up"],a:0,why:"sort out = régler, résoudre (un problème)."},
 {id:"F28-001",dom:"Phrasal verbs",skill:"Follow up",stem:"Remember to ____ on your application next week.",opts:["catch up","follow up","fill out","turn down"],a:1,why:"follow up (on) = relancer, faire un suivi."},
 {id:"F29-001",dom:"Phrasal verbs",skill:"Sign up for",stem:"Many employees ____ the new training programme.",opts:["handed in","looked into","signed up for","laid off"],a:2,why:"sign up for = s'inscrire à."},
 {id:"F30-001",dom:"Phrasal verbs",skill:"Find out",stem:"We need to ____ why sales dropped last month.",opts:["find out","put off","go over","check in"],a:0,why:"find out = découvrir, apprendre (une information)."},
 {id:"F31-001",dom:"Phrasal verbs",skill:"Take off",stem:"Sales really began to ____ after the ad campaign.",opts:["break down","take off","hand out","drop off"],a:1,why:"take off = décoller, démarrer fort (ventes, activité)."},
 {id:"F32-001",dom:"Phrasal verbs",skill:"Break down",stem:"The delivery van ____ on the motorway.",opts:["checked in","handed out","broke down","signed up"],a:2,why:"break down = tomber en panne."},
 {id:"F33-001",dom:"Phrasal verbs",skill:"Turn out",stem:"The event ____ to be a great success.",opts:["turned out","ran out","filled out","logged in"],a:0,why:"turn out = s'avérer, se révéler (finalement)."},
 {id:"G06-001",dom:"Synonymes",skill:"Paraphrases",stem:"« shipment » est le plus proche de :",opts:["delivery","payment","supplier","invoice"],a:0,why:"shipment ≈ delivery (le TOEIC adore reformuler)."},
 {id:"G10-001",dom:"Synonymes",skill:"Paraphrases",stem:"« The event has been postponed » signifie :",opts:["cancelled","delayed","organised","reduced"],a:1,why:"postpone ≈ delay (reporter), pas annuler."},
 {id:"G11-001",dom:"Synonymes",skill:"Paraphrases",stem:"« purchase » est le plus proche de :",opts:["sell","buy","return","store"],a:1,why:"purchase ≈ buy (acheter)."},
 {id:"G12-001",dom:"Synonymes",skill:"Paraphrases",stem:"« assist » est le plus proche de :",opts:["help","attend","watch","replace"],a:0,why:"assist ≈ help (aider). Attention : assist ≠ « assister à » (= attend)."},
 {id:"G13-001",dom:"Synonymes",skill:"Paraphrases",stem:"« require » est le plus proche de :",opts:["offer","need","reduce","accept"],a:1,why:"require ≈ need (exiger, demander)."},
 {id:"G14-001",dom:"Synonymes",skill:"Paraphrases",stem:"« obtain » est le plus proche de :",opts:["lose","share","send","get"],a:3,why:"obtain ≈ get/acquire (obtenir)."},
 {id:"G15-001",dom:"Synonymes",skill:"Paraphrases",stem:"« modify » est le plus proche de :",opts:["change","cancel","approve","repeat"],a:0,why:"modify ≈ change/alter (modifier)."},
 {id:"G16-001",dom:"Synonymes",skill:"Paraphrases",stem:"« resume » est le plus proche de :",opts:["finish","continue","summarise","reduce"],a:1,why:"resume ≈ continue/restart (reprendre). (≠ a résumé = a summary)."},
 {id:"G17-001",dom:"Synonymes",skill:"Paraphrases",stem:"« sufficient » est le plus proche de :",opts:["enough","extra","limited","empty"],a:0,why:"sufficient ≈ enough (suffisant)."},
 {id:"G18-001",dom:"Synonymes",skill:"Paraphrases",stem:"« complimentary » est le plus proche de :",opts:["expensive","free","optional","damaged"],a:1,why:"complimentary ≈ free of charge (gratuit, offert)."},
 {id:"G19-001",dom:"Synonymes",skill:"Paraphrases",stem:"« prompt » est le plus proche de :",opts:["late","careful","quick","polite"],a:2,why:"prompt ≈ quick/immediate (rapide, ponctuel)."},
 {id:"G20-001",dom:"Synonymes",skill:"Paraphrases",stem:"« reliable » est le plus proche de :",opts:["dependable","cheap","modern","temporary"],a:0,why:"reliable ≈ dependable/trustworthy (fiable)."},
 {id:"G21-001",dom:"Synonymes",skill:"Paraphrases",stem:"« mandatory » est le plus proche de :",opts:["optional","compulsory","occasional","temporary"],a:1,why:"mandatory ≈ compulsory/required (obligatoire)."},
 {id:"G22-001",dom:"Synonymes",skill:"Paraphrases",stem:"« additional » est le plus proche de :",opts:["fewer","missing","extra","final"],a:2,why:"additional ≈ extra (supplémentaire)."},
 {id:"G23-001",dom:"Synonymes",skill:"Paraphrases",stem:"« brief » est le plus proche de :",opts:["short","detailed","loud","official"],a:0,why:"brief ≈ short/concise (bref)."},
 {id:"G24-001",dom:"Synonymes",skill:"Paraphrases",stem:"« annual » est le plus proche de :",opts:["monthly","daily","weekly","yearly"],a:3,why:"annual ≈ yearly (annuel)."},
 {id:"G25-001",dom:"Synonymes",skill:"Paraphrases",stem:"« expand » est le plus proche de :",opts:["reduce","close","grow","move"],a:2,why:"expand ≈ grow/enlarge (se développer, s'agrandir)."},
 {id:"G26-001",dom:"Synonymes",skill:"Paraphrases",stem:"« vacant » est le plus proche de :",opts:["empty","busy","new","clean"],a:0,why:"vacant ≈ empty/available (vacant, libre)."},
 {id:"G27-001",dom:"Synonymes",skill:"Paraphrases",stem:"« durable » est le plus proche de :",opts:["fragile","long-lasting","cheap","heavy"],a:1,why:"durable ≈ long-lasting (résistant, durable)."},
 {id:"G28-001",dom:"Synonymes",skill:"Paraphrases",stem:"« confidential » est le plus proche de :",opts:["public","official","private","urgent"],a:2,why:"confidential ≈ private/secret (confidentiel)."},
 {id:"G29-001",dom:"Synonymes",skill:"Paraphrases",stem:"« terminate » est le plus proche de :",opts:["end","renew","extend","begin"],a:0,why:"terminate ≈ end (mettre fin à, résilier)."},
 {id:"G30-001",dom:"Synonymes",skill:"Paraphrases",stem:"« competent » est le plus proche de :",opts:["unavailable","capable","friendly","available"],a:1,why:"competent ≈ capable/skilled (compétent)."},
 {id:"G31-001",dom:"Synonymes",skill:"Paraphrases",stem:"« relevant » est le plus proche de :",opts:["useless","outdated","pertinent","recent"],a:2,why:"relevant ≈ pertinent/applicable (pertinent)."},
 {id:"G32-001",dom:"Synonymes",skill:"Paraphrases",stem:"« fee » est le plus proche de :",opts:["refund","discount","bonus","charge"],a:3,why:"fee ≈ charge/cost (frais, redevance)."},
 {id:"G33-001",dom:"Synonymes",skill:"Paraphrases",stem:"« innovative » est le plus proche de :",opts:["traditional","creative","cheap","reliable"],a:1,why:"innovative ≈ creative/new (innovant)."},
 {id:"G34-001",dom:"Synonymes",skill:"Paraphrases",stem:"« approximately » est le plus proche de :",opts:["exactly","barely","roughly","rarely"],a:2,why:"approximately ≈ roughly/about (environ)."},
 {id:"G35-001",dom:"Synonymes",skill:"Paraphrases de phrases",stem:"« Seating is limited » signifie :",opts:["Seats are free of charge","There are few seats available","Standing is not allowed","The room is very large"],a:1,why:"limited = en nombre réduit : il reste peu de places."},
 {id:"G36-001",dom:"Synonymes",skill:"Paraphrases de phrases",stem:"« Refreshments will be provided » signifie :",opts:["Free food and drinks will be available","Guests must bring their own food","The café will be closed","An extra fee will be charged"],a:0,why:"refreshments provided = boissons/collations offertes."},
 {id:"G37-001",dom:"Synonymes",skill:"Paraphrases de phrases",stem:"« The position requires extensive travel » signifie :",opts:["No travel is needed","A lot of travel is needed","Travel is only occasional","Travel is not allowed"],a:1,why:"extensive travel = de nombreux déplacements."},
 {id:"G38-001",dom:"Synonymes",skill:"Paraphrases de phrases",stem:"« Prices are subject to change » signifie :",opts:["Prices are fixed forever","Prices may change","Prices will be reduced","Prices include tax"],a:1,why:"subject to change = susceptible d'être modifié."},
 {id:"H01-001",dom:"Faux amis",skill:"False friends",stem:"« I attended the meeting » signifie :",opts:["j'ai attendu la réunion","j'ai assisté à la réunion","j'ai annulé la réunion","j'ai organisé la réunion"],a:1,why:"attend = assister à (≠ attendre = wait).",dx:{0:{t:"fauxami",note:"Faux ami parfait : *attend* ressemble a « attendre » mais signifie *assister a*. C'est exactement le piege vise."},2:{t:"sens",note:"« annuler » = *cancel/call off* : aucun rapport avec *attend*."},3:{t:"sens",note:"« organiser » = *organise/hold* : sens invente pour ce verbe."}}},
 {id:"H02-001",dom:"Faux amis",skill:"False friends",stem:"« Actually » se traduit par :",opts:["actuellement","en fait","finalement","éventuellement"],a:1,why:"actually = en fait (≠ actuellement = currently).",dx:{0:{t:"fauxami",note:"Faux ami n°1 : *actually* ne veut PAS dire « actuellement » (= *currently*). C'est la confusion testee."},2:{t:"sens",note:"« finalement » = *eventually/finally* : autre mot."},3:{t:"fauxami",note:"« eventuellement » traduit *possibly*, pas *actually* : deuxieme faux ami glisse dans les choix."}}},
 {id:"I08-001",dom:"Listening",skill:"Réponses indirectes",stem:"« Is the report finished? » → meilleure réponse :",opts:["It's already on her desk.","Yes, the report.","On the desk every day.","She is a manager."],a:0,why:"Réponse indirecte = oui implicite (il est déjà sur le bureau)."},
 {id:"J03-002",dom:"Reading",skill:"Inférence",stem:"« We apologise for any inconvenience caused. » On peut déduire :",opts:["The company changed ownership.","A problem occurred.","Prices increased.","A new manager was hired."],a:1,why:"Une excuse implique qu'un problème a eu lieu."},
 {id:"C07-001",dom:"Grammaire",skill:"Premier conditionnel",stem:"If demand increases, production ____.",opts:["increased","would increase","will increase","increasing"],a:2,why:"1er conditionnel : if + présent, … will + base verbale.",dx:{0:{t:"temps",note:"« increased » met la principale au passe : incompatible avec un *if + present*."},1:{t:"temps",note:"« would increase » est le 2e conditionnel (hypothese irreelle) ; ici le scenario est reel → *will*."},3:{t:"forme",note:"« increasing » n'est pas une forme conjuguee : il manque l'auxiliaire."}}},
 {id:"L08-001",dom:"Stratégie",skill:"Devinette",stem:"Une question sans réponse au TOEIC rapporte :",opts:["25%","50%","0%","75%"],a:2,why:"Réponse vide = 0 %. Au hasard = 25 %. Réponds toujours."},
 {id:"C04-001",dom:"Grammaire",skill:"Relative whose",stem:"The employee ____ application was accepted has already started work.",opts:["who","whose","which","where"],a:1,why:"« whose » marque la possession (dont la candidature)."},
 {id:"B02-001",dom:"Grammaire",skill:"Gérondif après recommend",stem:"The company recommends ____ safety procedures carefully.",opts:["follow","followed","following","to follow"],a:2,why:"« recommend » est suivi du gérondif → following."},
 {id:"C03-001",dom:"Grammaire",skill:"Relative réduite -ing",stem:"Employees ____ in the workshop must register online.",opts:["participating","participated","participate","participation"],a:0,why:"Relative réduite active → participle en -ing."},
 {id:"C05-001",dom:"Grammaire",skill:"Participe -ed/-ing",stem:"Customers were ____ by the delay.",opts:["frustrating","frustrated","frustrate","frustration"],a:1,why:"La personne ressent l'émotion → -ed (frustrated)."},
 {id:"C06-001",dom:"Grammaire",skill:"Participe -ed/-ing",stem:"The delay was ____.",opts:["frustrating","frustrated","frustrate","frustration"],a:0,why:"La chose provoque l'émotion → -ing (frustrating)."},
 {id:"C08-001",dom:"Grammaire",skill:"2e conditionnel",stem:"If I were the manager, I ____ the proposal.",opts:["approve","approved","would approve","will approve"],a:2,why:"2e conditionnel : if + prétérit, … would + base verbale."},
 {id:"C09-001",dom:"Grammaire",skill:"3e conditionnel",stem:"If they had prepared better, they ____ the contract.",opts:["win","would win","would have won","won"],a:2,why:"3e conditionnel : if + plus-que-parfait, … would have + participe."},
 {id:"P01-001",dom:"Connecteurs",skill:"Préposition comply",stem:"Employees must comply ____ company policy.",opts:["in","with","on","at"],a:1,why:"comply with (se conformer à)."},
 {id:"P02-001",dom:"Connecteurs",skill:"Préposition agree",stem:"The customer agreed ____ the new terms.",opts:["with","on","to","for"],a:2,why:"agree to + proposition ; agree with + personne."},
 {id:"A06-001",dom:"Grammaire",skill:"Familles de mots",stem:"The report was completed ____.",opts:["success","successful","successfully","succeed"],a:2,why:"Après le verbe, il faut un adverbe → successfully."},
 {id:"D10-001",dom:"Connecteurs",skill:"Between vs Among",stem:"The prize was divided ____ the three winners.",opts:["between","among","beside","across"],a:1,why:"among pour plus de deux ; between pour deux."},
 {id:"D11-001",dom:"Connecteurs",skill:"Since vs For",stem:"She has worked here ____ 2021.",opts:["for","since","during","by"],a:1,why:"since + point de départ (2021) ; for + durée."},
 {id:"V01-001",dom:"Vocabulaire",skill:"Vocabulaire en contexte",stem:"We need to ____ the meeting to next week.",opts:["postpone","attend","assist","resume"],a:0,why:"postpone = reporter ; attend = assister à."},
 {id:"V02-001",dom:"Vocabulaire",skill:"Vocabulaire en contexte",stem:"Please ____ the attached document carefully.",opts:["assist","review","regard","attend"],a:1,why:"review = examiner / relire."},
 {id:"D12-001",dom:"Connecteurs",skill:"Due to",stem:"The flight was delayed ____ a storm.",opts:["because","due to","although","despite"],a:1,why:"due to + nom ; because + sujet et verbe."},
 {id:"A07-001",dom:"Grammaire",skill:"Comparatif",stem:"This model is ____ than the previous one.",opts:["efficient","more efficient","most efficient","efficiently"],a:1,why:"Adjectif long → more + adjectif."},
 {id:"A08-001",dom:"Grammaire",skill:"Superlatif",stem:"It is the ____ option available.",opts:["affordable","more affordable","most affordable","affordably"],a:2,why:"Superlatif → the most + adjectif long."},
 {id:"A09-001",dom:"Grammaire",skill:"Much / Many",stem:"We don't have ____ time before the deadline.",opts:["many","much","few","a number of"],a:1,why:"time est indénombrable → much."},
 {id:"A10-001",dom:"Grammaire",skill:"Few / Little",stem:"____ employees attended the optional session.",opts:["Few","Little","Much","A little"],a:0,why:"employees est dénombrable → Few."},
 {id:"C10-001",dom:"Grammaire",skill:"Present perfect",stem:"She ____ here for five years.",opts:["works","worked","has worked","is working"],a:2,why:"Durée jusqu'à maintenant (for five years) → present perfect."},
 {id:"C11-001",dom:"Grammaire",skill:"Discours rapporté",stem:"He said he ____ finish by Friday.",opts:["will","would","is","has"],a:1,why:"Discours rapporté au passé : will → would."},
 {id:"C12-001",dom:"Grammaire",skill:"Relative which",stem:"The product, ____ was launched in May, sold well.",opts:["who","which","whose","where"],a:1,why:"Pour une chose, on utilise which."},
 {id:"P03-001",dom:"Connecteurs",skill:"Préposition responsible",stem:"She is responsible ____ the new project.",opts:["of","for","to","with"],a:1,why:"responsible for (responsable de)."},
 {id:"D13-001",dom:"Connecteurs",skill:"However (contraste)",stem:"The product is very popular; ____, it is quite expensive.",opts:["however","therefore","moreover","because"],a:0,why:"however = cependant (contraste entre deux idées)."},
 {id:"D14-001",dom:"Connecteurs",skill:"Therefore (conséquence)",stem:"Sales rose sharply; ____, the company hired more staff.",opts:["however","therefore","although","despite"],a:1,why:"therefore = par conséquent (conséquence logique)."},
 {id:"D15-001",dom:"Connecteurs",skill:"Moreover (addition)",stem:"The hotel is very central. ____, breakfast is included.",opts:["Otherwise","Because","Moreover","However"],a:2,why:"moreover = de plus, en outre (ajout d'information)."},
 {id:"D16-001",dom:"Connecteurs",skill:"Nevertheless (concession)",stem:"It was raining heavily; ____, the outdoor event went ahead.",opts:["therefore","moreover","so","nevertheless"],a:3,why:"nevertheless = néanmoins, malgré tout."},
 {id:"D17-001",dom:"Connecteurs",skill:"In addition to + nom",stem:"____ his salary, he receives an annual bonus.",opts:["In addition to","Moreover","However","Therefore"],a:0,why:"in addition to + nom = en plus de (≠ « in addition » employé seul)."},
 {id:"D18-001",dom:"Connecteurs",skill:"As a result",stem:"The flight was cancelled; ____, we missed the meeting.",opts:["even though","as a result","on the other hand","in addition"],a:1,why:"as a result = en conséquence, du coup."},
 {id:"D19-001",dom:"Connecteurs",skill:"On the other hand",stem:"The first option is cheap. ____, it is rather risky.",opts:["Therefore","Moreover","On the other hand","As a result"],a:2,why:"on the other hand = d'un autre côté (opposition)."},
 {id:"D20-001",dom:"Connecteurs",skill:"Whereas (opposition)",stem:"Sales increased in Asia, ____ they fell in Europe.",opts:["therefore","moreover","because","whereas"],a:3,why:"whereas = tandis que, alors que (oppose deux propositions)."},
 {id:"D21-001",dom:"Connecteurs",skill:"Unless (condition)",stem:"You won't get a refund ____ you keep the receipt.",opts:["unless","although","because","despite"],a:0,why:"unless = à moins que, sauf si (= if not)."},
 {id:"D22-001",dom:"Connecteurs",skill:"In order to + verbe",stem:"The deadline was extended ____ give staff more time.",opts:["due to","in order to","because of","as a result"],a:1,why:"in order to + base verbale = afin de (but)."},
 {id:"D23-001",dom:"Connecteurs",skill:"So that + proposition",stem:"Please arrive early ____ we can start the meeting on time.",opts:["due to","because of","so that","in spite of"],a:2,why:"so that + sujet + verbe = pour que, afin que (but)."},
 {id:"D24-001",dom:"Connecteurs",skill:"Even though + proposition",stem:"____ the price increased, demand stayed high.",opts:["Because","Therefore","So","Even though"],a:3,why:"even though = bien que (concession, suivi d'une proposition)."},
 {id:"D25-001",dom:"Connecteurs",skill:"In spite of + nom",stem:"____ the delay, the project was completed on budget.",opts:["In spite of","Although","Even though","Because"],a:0,why:"in spite of + nom = malgré (comme « despite »)."},
 {id:"D26-001",dom:"Connecteurs",skill:"Provided that (condition)",stem:"You can take Friday off ____ you finish the report first.",opts:["although","provided that","however","therefore"],a:1,why:"provided that = à condition que."},
 {id:"D27-001",dom:"Connecteurs",skill:"Otherwise",stem:"Submit the form today; ____, you'll miss the deadline.",opts:["therefore","moreover","otherwise","however"],a:2,why:"otherwise = sinon, faute de quoi."},
 {id:"D28-001",dom:"Connecteurs",skill:"Meanwhile",stem:"The manager was abroad; ____, the team kept working.",opts:["therefore","although","because","meanwhile"],a:3,why:"meanwhile = pendant ce temps."},
 {id:"D29-001",dom:"Connecteurs",skill:"Consequently",stem:"Production costs rose sharply; ____, prices were increased.",opts:["Consequently","However","Moreover","Although"],a:0,why:"consequently = par conséquent."},
 {id:"D30-001",dom:"Connecteurs",skill:"While (contraste)",stem:"____ some clients prefer email, others prefer phone calls.",opts:["Due to","While","Because of","Therefore"],a:1,why:"while = alors que, tandis que (contraste entre deux faits)."},
 {id:"D31-001",dom:"Connecteurs",skill:"As long as (condition)",stem:"You may use the laboratory ____ you wear safety goggles.",opts:["despite","however","as long as","therefore"],a:2,why:"as long as = tant que, à condition que."},
 {id:"D32-001",dom:"Connecteurs",skill:"Although + proposition",stem:"____ the team was small, it met all of its targets.",opts:["Because of","Due to","Despite","Although"],a:3,why:"although + proposition = bien que (≠ despite + nom)."},
 {id:"D33-001",dom:"Connecteurs",skill:"Despite + nom",stem:"____ the high cost, the firm purchased the new software.",opts:["Despite","Although","Because","Therefore"],a:0,why:"despite + nom = malgré (≠ although + proposition)."},
 {id:"D34-001",dom:"Connecteurs",skill:"Such as (exemples)",stem:"The kit includes accessories ____ cables and a charger.",opts:["so that","such as","in order to","as a result"],a:1,why:"such as = tel(le)s que (introduit des exemples)."},
 {id:"D35-001",dom:"Connecteurs",skill:"In contrast",stem:"Last year was difficult. ____, this year looks very promising.",opts:["Therefore","So","In contrast","Moreover"],a:2,why:"in contrast = en revanche, par contraste."},
 {id:"D36-001",dom:"Connecteurs",skill:"Since (cause)",stem:"____ the report was incomplete, the meeting was postponed.",opts:["Despite","However","Therefore","Since"],a:3,why:"since (ici) = puisque, comme (cause)."},
 {id:"D37-001",dom:"Connecteurs",skill:"Furthermore (addition)",stem:"The plan is too expensive. ____, it is completely unrealistic.",opts:["Furthermore","However","Otherwise","Because"],a:0,why:"furthermore = de plus, en outre."},
 {id:"D38-001",dom:"Connecteurs",skill:"Now that (cause)",stem:"____ the system has been updated, you can log in again.",opts:["Despite","Now that","However","In spite of"],a:1,why:"now that = maintenant que (cause liée au présent)."},
 {id:"D39-001",dom:"Connecteurs",skill:"Either … or",stem:"You can pay ____ by card or in cash.",opts:["neither","either","both","whether"],a:1,why:"either … or = soit … soit."},
 {id:"D40-001",dom:"Connecteurs",skill:"Whether (question indirecte)",stem:"Please let me know ____ you can attend the workshop.",opts:["whether","unless","despite","although"],a:0,why:"whether = si (question indirecte avec une alternative)."},
 {id:"A11-001",dom:"Grammaire",skill:"So / Such",stem:"It was ____ a busy day that we skipped lunch.",opts:["so","such","very","too"],a:1,why:"such + (a) + nom ; so + adjectif seul."},
 {id:"A12-001",dom:"Grammaire",skill:"Enough",stem:"The candidate was experienced ____ for the role.",opts:["enough","too","very","much"],a:0,why:"adjectif + enough (assez expérimenté)."},
 {id:"V03-001",dom:"Vocabulaire",skill:"Vocabulaire en contexte",stem:"All employees are ____ to attend the training.",opts:["required","requested","acquired","inquired"],a:0,why:"be required to = être tenu de."}
];
